(() => {
'use strict';
const $=s=>document.querySelector(s);
const state={role:null,anchor:new Date(),week:null,current:null,reschedule:null,token:null,firstRender:true};
const STALE_MS=120000;
if('scrollRestoration' in history)history.scrollRestoration='manual';
const SLOT_TIMES=(()=>{const out=[];for(let m=8*60;m<=17*60;m+=20){const end=m+20;if(m<14*60&&end>12*60+30)continue;out.push(`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`)}return out})();
function pad(n){return String(n).padStart(2,'0')} function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseISO(s){const [y,m,d]=String(s).slice(0,10).split('-').map(Number);return new Date(y,m-1,d)} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function mondayOf(d){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(12,0,0,0);return x}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cap(s){return String(s||'').toLowerCase().replace(/(^|\s|[-])\p{L}/gu,m=>m.toUpperCase())}
function fmtShort(d){return new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short'}).format(d).replace('.','')}
function fmtLong(d){return new Intl.DateTimeFormat('es-EC',{weekday:'long',day:'numeric',month:'long'}).format(d)}
function timeParts(v){const [h,m]=String(v||'00:00').split(':').map(Number);return {main:`${(h%12)||12}:${pad(m)}`,period:h>=12?'PM':'AM'}} function fmtTime12(v){const t=timeParts(v);return `${t.main} ${t.period}`}
function weekLabel(mon){return `${fmtShort(addDays(mon,3))} – ${new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short',year:'numeric'}).format(addDays(mon,5)).replace('.','')}`}
function statusNorm(v){const s=String(v||'PENDIENTE').toUpperCase();if(['CONFIRMADA','CONFIRMADO','SI','SÍ'].includes(s))return'confirmed';if(['CANCELADA','CANCELADO','NO','NO_ASISTIRA'].includes(s))return'cancelled';if(s==='REAGENDADA')return'rescheduled';return'pending'}
function statusLabel(v){const s=statusNorm(v);return s==='confirmed'?'Confirmada':s==='cancelled'?'No asistirá':s==='rescheduled'?'Reagendada':'Pendiente'}
function cacheKey(){return `revelo-agenda-week:${iso(mondayOf(state.anchor))}`} function metaKey(){return cacheKey()+':ts'}
function setSync(text,online){$('#syncText').textContent=text;$('#syncDot').classList.toggle('online',!!online)} function timeNow(){return new Intl.DateTimeFormat('es-EC',{hour:'numeric',minute:'2-digit'}).format(new Date())}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
function storeToken(){const p=new URLSearchParams(location.search),h=new URLSearchParams(String(location.hash||'').replace(/^#/,'')),fragment=h.get('token'),q=p.get('token'),saved=localStorage.getItem('revelo_mobile_token');state.token=fragment||q||saved||'';if(fragment||q)localStorage.setItem('revelo_mobile_token',state.token);p.delete('token');p.set('v','4.3.34');const hash=state.token?`#token=${encodeURIComponent(state.token)}`:'';history.replaceState({},'',`${location.pathname}?${p.toString()}${hash}`) }
async function api(url,opts={}){const headers={...(opts.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(url,{...opts,headers,cache:'no-store'});if(!r.ok){let msg=`Error ${r.status}`;try{const d=await r.json();msg=d.detail||msg}catch{}throw Error(msg)}return r.status===204?null:r.json()}
function openModal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden');document.body.style.overflow='hidden'} function closeModal(){$('#modalBackdrop').classList.add('hidden');document.body.style.overflow='';state.current=null;state.reschedule=null}
$('#closeModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()}
async function bootstrap(){storeToken();if(!state.token){fatal('Este enlace no tiene acceso válido. Ábrelo desde Configuración → Agenda y WhatsApp.');return}try{const me=await api('/api/mobile/me');state.role=me.role;document.body.classList.toggle('doctor-mode',state.role==='doctor');$('#modeLabel').textContent=state.role==='doctor'?'Doctor · solo lectura':'Recepción · agendamiento';$('#agendaHint').textContent=state.role==='doctor'?'Solo lectura · los cambios se realizan desde Recepción.':'Toca un espacio libre para agendar.';await loadWeek(false);if('serviceWorker'in navigator)navigator.serviceWorker.register('/mobile/sw.js?v=4.3.34',{scope:'/mobile/',updateViaCache:'none'}).then(r=>r.update().catch(()=>{})).catch(()=>{})}catch(e){fatal(e.message)}}
function fatal(msg){setSync('Acceso no disponible',false);$('#agendaContainer').innerHTML=`<div class="loading-card"><b>No se pudo abrir la agenda</b><br>${esc(msg)}</div>`}
async function loadWeek(force=false){const key=cacheKey(),cached=localStorage.getItem(key),ts=Number(localStorage.getItem(metaKey())||0);if(cached){try{state.week=JSON.parse(cached);render();setSync('Copia guardada',false)}catch{}}const fresh=Date.now()-ts<STALE_MS;if(!force&&fresh&&state.week){setSync(`Actualizada ${new Intl.DateTimeFormat('es-EC',{hour:'numeric',minute:'2-digit'}).format(new Date(ts))}`,true);return}if(document.hidden&&!force)return;try{const d=await api(`/api/mobile/agenda/week?anchor=${encodeURIComponent(iso(state.anchor))}`);state.week=d;localStorage.setItem(key,JSON.stringify(d));localStorage.setItem(metaKey(),String(Date.now()));render();setSync(`Actualizada ${timeNow()}`,true)}catch(e){if(state.week)setSync('Sin conexión · usando copia guardada',false);else fatal(e.message)}}
function render(){if(!state.week)return;state.anchor=parseISO(state.week.week_start||iso(state.anchor));$('#weekTitle').textContent=weekLabel(parseISO(state.week.week_start));syncWeekNav();renderGrid();renderSummary();if(state.firstRender){state.firstRender=false;requestAnimationFrame(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});const first=document.querySelector('.first-slot-time');if(first)first.scrollIntoView({block:'nearest',inline:'nearest'})})}}
function rowParts(row){const a=row.appointment||{},st=row.staged||{},p=row.patient||{};return {isUnlinked:!!st?.id,entityId:st?.id||a?.id||null,date:String(st?.fecha||a?.fecha||'').slice(0,10),time:st?.hora||a?.hora,name:p?.nombre||st?.nombre||'Paciente',note:String(a?.nota||'').trim(),status:a?.estado||'PENDIENTE',source:row.source_type||''}}
function renderGrid(){const days=state.week.days||[],maps=days.map(day=>{const m=new Map();(day.appointments||[]).forEach(r=>{const x=rowParts(r);if(x.time)m.set(x.time,r)});return m});const out=['<div class="schedule-grid"><div class="grid-corner"></div>'];days.forEach(d=>out.push(`<div class="day-head"><b>${esc(String(d.label||'').toUpperCase())}</b><span>${fmtShort(parseISO(d.date))}</span></div>`));let lunch=false;for(const t of SLOT_TIMES){if(!lunch&&t==='14:00'){out.push('<div class="time-cell lunch-time"><span class="time-main">12:30</span><small>PM</small></div><div class="lunch-label">ALMUERZO · 12:30 PM – 2:00 PM</div>');lunch=true}const tp=timeParts(t);out.push(`<div class="time-cell ${t==='08:00'?'first-slot-time':''}"><span class="time-main">${tp.main}</span><small>${tp.period}</small></div>`);days.forEach((d,i)=>{const r=maps[i].get(t);out.push(r?appointmentCell(r):freeCell(d.date,t))})}out.push('</div>');$('#agendaContainer').innerHTML=out.join('');document.querySelectorAll('[data-free]').forEach(el=>el.onclick=()=>{if(state.role==='reception')state.reschedule?performReschedule(el.dataset.date,el.dataset.time):openNew(el.dataset.date,el.dataset.time)});document.querySelectorAll('[data-item]').forEach(el=>el.onclick=()=>openDetail(JSON.parse(el.dataset.item))) }
function freeCell(date,time){const tp=timeParts(time);return `<div class="slot-cell free ${state.role==='reception'?'reception':''} ${time==='08:00'?'first-slot':''}" data-free data-date="${date}" data-time="${time}"><div class="free-text"><span class="free-time">${tp.main} ${tp.period}</span><span class="free-label">Disponible</span></div></div>`}
function appointmentCell(row){const x=rowParts(row),st=statusNorm(x.status),packed=esc(JSON.stringify({u:x.isUnlinked,id:x.entityId,date:x.date,time:x.time,name:x.name,note:x.note,status:x.status,source:x.source}));const note=x.note?` <span class="appointment-note">(${esc(x.note)})</span>`:'';return `<div class="slot-cell ${st}"><button class="appointment-card" type="button" data-item="${packed}"><span class="appointment-name">${esc(x.name)}${note}</span><span class="appointment-status"><i class="status-dot ${st}"></i>${statusLabel(x.status)}</span></button></div>`}
function renderSummary(){const rows=(state.week.days||[]).flatMap(d=>d.appointments||[]),total=(state.week.days||[]).length*SLOT_TIMES.length;$('#sumAppointments').textContent=rows.length;$('#sumConfirmed').textContent=rows.filter(r=>statusNorm(rowParts(r).status)==='confirmed').length;$('#sumPending').textContent=rows.filter(r=>['pending','rescheduled'].includes(statusNorm(rowParts(r).status))).length;$('#sumFree').textContent=Math.max(0,total-rows.length)}
function openNew(date,time){const tpl=$('#newAppointmentTemplate').content.cloneNode(true);$('#modalContent').innerHTML='';$('#modalContent').append(tpl);$('#modalBackdrop').classList.remove('hidden');document.body.style.overflow='hidden';$('#newDateLabel').textContent=cap(fmtLong(parseISO(date)));$('#newTimeLabel').textContent=fmtTime12(time);const sync=()=>$('#saveNew').disabled=!($('#bookingName').value.trim()&&$('#bookingPhone').value.trim());$('#bookingName').oninput=sync;$('#bookingPhone').oninput=sync;$('#cancelNew').onclick=closeModal;$('#saveNew').onclick=()=>saveNew(date,time);sync()}
async function saveNew(date,time){const b=$('#saveNew');b.disabled=true;b.textContent='Guardando…';try{await api('/api/mobile/appointments',{method:'POST',body:JSON.stringify({nombre:$('#bookingName').value.trim(),celular:$('#bookingPhone').value.trim(),fecha:date,hora:time})});closeModal();toast('Cita guardada');invalidateWeek();await loadWeek(true)}catch(e){toast(e.message);b.disabled=false;b.textContent='Guardar cita'}}
function openDetail(x){state.current=x;const readonly=state.role==='doctor',note=x.note?`<div class="detail-note appointment-detail-note"><b>Nota:</b> ${esc(x.note)}</div>`:'';openModal(`<div class="modal-kicker">DETALLE DE CITA</div><h2>${esc(x.name)}</h2><div class="detail-card"><div><span>Fecha</span><strong>${esc(cap(fmtLong(parseISO(x.date))))}</strong></div><div><span>Hora</span><strong>${esc(fmtTime12(x.time))}</strong></div><div><span>Estado</span><strong>${esc(statusLabel(x.status))}</strong></div></div>${note}${readonly?'<div class="read-only-note">Solo lectura · los cambios se realizan desde Recepción.</div>':`<div class="modal-actions"><button class="danger-btn" id="deleteAppointment">Cancelar cita</button><button class="primary-btn" id="rescheduleAppointment">Reagendar</button></div>`}`);if(!readonly){$('#deleteAppointment').onclick=()=>removeAppointment(x);$('#rescheduleAppointment').onclick=()=>beginReschedule(x)}}
async function removeAppointment(x){if(!confirm('¿Cancelar esta cita y liberar el horario?'))return;try{await api(x.u?`/api/mobile/unlinked/${x.id}`:`/api/mobile/appointments/${x.id}`,{method:'DELETE'});closeModal();toast('Horario liberado');invalidateWeek();await loadWeek(true)}catch(e){toast(e.message)}}
function beginReschedule(x){state.reschedule=x;closeModal();state.reschedule=x;toast('Toca el nuevo horario libre')}
async function performReschedule(date,time){const x=state.reschedule;if(!x)return;if(!confirm(`¿Reagendar a ${cap(fmtLong(parseISO(date)))} · ${fmtTime12(time)}?`))return;try{await api(x.u?`/api/mobile/unlinked/${x.id}`:`/api/mobile/appointments/${x.id}`,{method:'PUT',body:JSON.stringify({fecha:date,hora:time})});state.reschedule=null;toast('Cita reagendada');invalidateWeek();await loadWeek(true)}catch(e){toast(e.message)}}
function invalidateWeek(){localStorage.removeItem(cacheKey());localStorage.removeItem(metaKey())}
function currentWeekMonday(){return mondayOf(new Date())}function isCurrentWeek(){return iso(mondayOf(state.anchor))===iso(currentWeekMonday())}function syncWeekNav(){const b=$('#prevWeek');if(!b)return;const current=isCurrentWeek();b.disabled=current;b.classList.toggle('hidden-nav',current);b.setAttribute('aria-hidden',current?'true':'false')}
$('#prevWeek').onclick=()=>{const target=addDays(mondayOf(state.anchor),-7),min=currentWeekMonday();state.anchor=target<min?min:target;state.week=null;state.reschedule=null;loadWeek(false)};$('#nextWeek').onclick=()=>{state.anchor=addDays(state.anchor,7);state.week=null;state.reschedule=null;loadWeek(false)};$('#refreshBtn').onclick=()=>loadWeek(true);
document.addEventListener('visibilitychange',()=>{if(!document.hidden){const ts=Number(localStorage.getItem(metaKey())||0);if(Date.now()-ts>=STALE_MS)loadWeek(false)}});
bootstrap();
})();
